[providers]
- "php"
- "node"

[variables]
NODE_OPTIONS = "--max_old_space_size=512"
COMPOSER_IGNORE_PLATFORM_REQS = "1"

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"